### ISSUE TITLE
Add stopword list for German

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#16]
https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

**Comment by zwif** [comment]
Hey @eklem,
can you provide some information on how you retrieved the list?
Thank you!

**Comment by eklem** [comment]
I don't remember. I see it's lacking info on who created it originally and license. I'll figure it out or remove it. Most probably it's from another open-source library. Was that why you were asking?

**Comment by zwif** [comment]
No, it's not due to licensing at all. I am just gathering words for my own stopword list in german and thought you might had a good source for me.

**Comment by eklem** [comment]
It's this library I think: [stopwords-iso/stopwords-de](https://github.com/stopwords-iso/stopwords-de). Check out that one, or if you want to create a list of stopwords yourself, you can use the [stopword-trainer](https://github.com/eklem/stopword-trainer).
