### ISSUE TITLE
The library considers the verb "see" as a stop word!

### ISSUE THREAD

**Issue by behzadmoradi** [fergiemcdowall/stopword#194]
In a string such as `she loves to see him`, the verb `see` is taken as a stop word and is removed from the final array which is not right

**Comment by fergiemcdowall** [comment]
Yes, I _see_ what you mean😉. A quick google confirms that some English stopword lists include "see", whilst others drop it. At this stage there could be an argument for referring to another list, or for popular languages like English, being able to choose, or even compose lists from pre-existing stopword lists.

**Comment by eklem** [comment]
From a theoretical standpoint it's not correct, but sometimes it will be correct in practical use. When the word see is used in a lot if documents. I thought of generating stopword lists, sotted on stopwordiness. But for now, that's too much work. We can take it out. Can you create a PR?

I've created a library to generate lists of stopwords where you can redlist words that you want to keep (as opposed to a stopword list being a blacklist). It will also be better for tribe langue within an organization or group of people. https://github.com/eklem/stopword-trainer/

**Comment by eklem** [comment]
Also, stopword-trainer can be used to to continually update your list if stopwords.

**Comment by behzadmoradi** [comment]
@eklem When the NPM repo is going to get updated?

**Comment by eklem** [comment]
Thanks! I think I'll get it done later tonight.

**Comment by eklem** [comment]
@behzadmoradi, version 1.0.8 is published to NPM 😄 
Thanks for the PR and issue.
