### ISSUE TITLE
ES6 features in code base - a breaking change

### ISSUE THREAD

**Issue by ulfryk** [fergiemcdowall/stopword#25]
Version to `1.1.3` (or `1.1.2`) introduces ES6 `=>` function syntax in code published to NPM which seems to be a breaking change… And there is no info about it (can't find any release notes no changelog).

**Comment by eklem** [comment]
It happened [January 26th](https://github.com/fergiemcdowall/stopword/commit/67a7331d057bc744f4ce5a0a97d055be36668ba3) I think.

**Comment by eklem** [comment]
When it ended up on [NPM](http://npmjs.com/), I'm not sure.

**Comment by ulfryk** [comment]
I verified - it's version `1.1.2` that introduced ` => `.

**Comment by eklem** [comment]
Yes, it was a (too) long time between 0.1.1 and 0.1.2:

```javascript
   { modified: '2017-06-23T09:41:51.477Z',
     created: '2015-05-28T16:04:05.029Z',
     '0.0.0': '2015-05-28T16:04:05.029Z',
     '0.0.1': '2015-05-29T11:39:48.690Z',
     '0.0.2': '2015-05-29T12:01:40.962Z',
     '0.0.3': '2015-05-29T12:29:54.456Z',
     '0.0.4': '2016-03-15T09:04:33.748Z',
     '0.0.5': '2016-03-15T09:44:56.427Z',
     '0.0.6': '2016-04-05T12:14:31.634Z',
     '0.0.7': '2016-06-20T12:44:45.676Z',
     '0.1.0': '2016-08-29T11:27:16.374Z',
     '0.1.1': '2016-09-02T09:22:21.556Z',
     '0.1.2': '2017-06-23T09:12:18.371Z',
     '0.1.3': '2017-06-23T09:39:47.218Z' }
```

**Comment by eklem** [comment]
Sorry for causing problems!

**Comment by ulfryk** [comment]
Not a huge problem (for now we'll use `1.1.1`) :) It's great that this lib exists and we can use it!

Anyway - it would be nice if there was some changelog or release notes on GH.

… and maybe you can introduce a `patch` that would get the lib back to ES5 ?

**Comment by eklem** [comment]
We'll be better at release notes on GH, but I can't promise a patch. I'll give it a try if I find some time.

**Comment by fergiemcdowall** [comment]
+1 for release tagging and changelog :)

**Comment by eklem** [comment]
So @ulfryk,
If I understand you right, it would work if I change this:
```javascript
return tokens.filter(value => stopwords.indexOf(value.toLowerCase()) === -1);
```

```javascript
return tokens.filter(function (value) {
  if (stopwords.indexOf(value.toLowerCase()) === -1)
    return value
})
```

**Comment by ulfryk** [comment]
Right :)

**Comment by ulfryk** [comment]
```
return tokens.filter(function (value) {
  return stopwords.indexOf(value.toLowerCase()) === -1);
})
```

**Comment by fergiemcdowall** [comment]
@ulfryk want to submit a pull request?

**Comment by ulfryk** [comment]
probably I'll do that ;)

**Comment by ulfryk** [comment]
I see that version `1.1.4` was just released to NPM now…

**Comment by eklem** [comment]
0.1.4 was just to get the changelog in the Readme file onto NPM

**Comment by eklem** [comment]
Fix available on [npmjs.com/package/stopword](https://www.npmjs.com/package/stopword) @ulfryk Can you test it?

**Comment by ulfryk** [comment]
Looks good now! THX

**Comment by eklem** [comment]
Cool! Just open an issue if there is something else.
