### ISSUE TITLE
ES6 import destructuring

### ISSUE THREAD

**Issue by ianengelbrecht** [fergiemcdowall/stopword#262]
It would be good to be able to use ES6 imports:

import {removeStopwords, hr, cs, zu} from 'stopword'

**Comment by eklem** [comment]
Yes. That would be good! I'm restructuring bundling/building a little, and will add esm-module, and I'll add it so you get to the functions and variables/arrays directly.

**Comment by eklem** [comment]
But, for the stopword arrays, I'm guessing it would be good to have something like `swHr`, `swCs`, `swZu` since you could have other language arrays that are not stopwords?

**Comment by ianengelbrecht** [comment]
I think it will be fine if you leave them as is. Users can alias them in the destructuring. Thanks! 😁

**Comment by eklem** [comment]
I'm on the case. It will take some days or a week since I have a lot of other changes I want to get out the door at the same time.

**Comment by eklem** [comment]
Fixed in v2-branch. Will use some time to a couple of other issues before wrapping up and publishing. Like swapping language codes from ISO 639-1 Code to ISO 639-2 Code

#255

**Comment by eklem** [comment]
@ianengelbrecht I'll see if I can get a v3.0.0.rc.1 out later today. Just need some documentation changes.

**Comment by eklem** [comment]
published it under tag: next, so:
`npm install stopword@next`

It's 2.0.0-rc.1 for including in a dependency list.

Shout out if any problems!
