### ISSUE TITLE
Make it ready for nodejs v.7

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#28]
Some dependencies needs an upgrade

**Comment by eklem** [comment]
I'll see if I can add tests for all the latest versions of Node.

**Comment by fergiemcdowall** [comment]
I think it just needs to be updated here: https://github.com/fergiemcdowall/stopword/blob/master/.travis.yml

**Comment by eklem** [comment]
I'll test it and figure out a little more about Travis

**Comment by fergiemcdowall** [comment]
It should run automatically in travis once the file is updated

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by eklem** [comment]
Fixed with [Testing on more versions of Node (4,6,8 and 9) ](https://github.com/fergiemcdowall/stopword/commit/55b807b8724d3b820300b077d093389de7474988) and [Removing tests for version 5 of NodeJS ](https://github.com/fergiemcdowall/stopword/commit/cb17df42791ef6e0455a0129846a7b3e11141eee)

**Comment by fergiemcdowall** [comment]
👍 👍
