### ISSUE TITLE
Stop Word list for Punjabi GUrmukhi

### ISSUE THREAD

**Issue by navroz441** [fergiemcdowall/stopword#287]
I am trying to make punjabi text fo through NLP piepeline.
I need a list of punjabi stopwords so that i can complete my task.
i am trying to create this system on python3

**Comment by eklem** [comment]
We have that, but it's in JavaScript. But the list is just an array. You can copy and reference the license over in your Python code?
https://github.com/fergiemcdowall/stopword/blob/master/src/stopwords_panGu.js

**Comment by eklem** [comment]
You have the tests, and one of them is for [Punjabi Gurmukhi](https://github.com/fergiemcdowall/stopword/blob/master/test/test.cjs.js#L246-L251):

```javaScript
const { removeStopwords, panGu }  = require('stopword')
const oldString = 'ਅਫਗਾਨੀਸਤਾਨ ਦੇ ਲਈ ਇੰਟਰਨੈੱਟ ਦਾ ਟਾੱਪ-ਲੈੱਵਲ ਡੋਮੇਨ ਦੇਸ਼ ਕੋਡ ਹੈ ਇਹ ਡੋਮੇਨ ਏ ਐਫ ਜੀ ਐਨ ਆਈ ਸੀ ਦੇ ਦੁਆਰਾ ਚਲਾਇਆ ਜਾਂਦਾ ਹੈ, ਜੋ ਅਫਗਾਨੀ ਸਰਕਾਰ ਅਤੇ ਯੂਨਾਈਟਡ ਨੇਸ਼ਨਜ਼ ਦੇ ਥੱਲੇ ਆਂਦਾ ਹੈ'.split(' ')
const newString = removeStopwords(oldString, panGu)
// newString === ['ਅਫਗਾਨੀਸਤਾਨ', 'ਇੰਟਰਨੈੱਟ', 'ਟਾੱਪ-ਲੈੱਵਲ', 'ਡੋਮੇਨ', 'ਕੋਡ', 'ਡੋਮੇਨ', 'ਐਫ', 'ਐਨ', 'ਚਲਾਇਆ', 'ਹੈ,', 'ਅਫਗਾਨੀ', 'ਯੂਨਾਈਟਡ', 'ਨੇਸ਼ਨਜ਼', 'ਥੱਲੇ', 'ਆਂਦਾ']
```

**Comment by eklem** [comment]
I'm closing this issue now, @navroz441. Feel free to open it again if any  more/new questions.
