### ISSUE TITLE
Make it run in the browser

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#29]
A stopword module can come in handy a lot of places, also in the browser. And it doesn't have any dependencies (only devDependencies). What would it take to run it in the browser, @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
It should just work with browserify. If we were super organised we could also create a 'dist' file that contained a browser-runnable version

**Comment by eklem** [comment]
Cool. So to be super organised, we need to browserify it for each new release?

**Comment by fergiemcdowall** [comment]
Yes, and that step can be easily added to the scripts

**Comment by eklem** [comment]
Nice! I want to try getting the [eklem-headline-parser](https://github.com/eklem/eklem-headline-parser) to run in the browser, and base it on stopword for stopword removal. Then I can add arrays of important keywords to the document for categorizing before sending the document to indexing.

**Comment by FabricioRHS** [comment]
Implementing this functionality will be very good. 👍 
>Make it run in the browser

**Comment by eklem** [comment]
It will happen, @FabricioRHS, we're just not sure how long it'll take 😃

**Comment by eklem** [comment]
And it would be a nice part of the tool-chain together with the [crawler-in-browser](https://github.com/eklem/crawler-in-browser) module.

**Comment by eklem** [comment]
Ok, so have a [`build`-step under scripts](https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) and [check out how to use the browserify API from a script](https://github.com/browserify/browserify#api-example).

**Comment by eklem** [comment]
Look at how search-index is doing this.

**Comment by eklem** [comment]
I'll test to browserify it and se if I can get something working. If yes, look into scripting it, and then we need some tests working also.

**Comment by eklem** [comment]
```console
npx webpack-cli --mode development lib/stopword.js -o dist/stopword-bundle.js
```
Set it up to build automatically
