### ISSUE TITLE
Add stop words for more languages from extra-stopwords:  Albanian, Belarusian, Icelandic, Mongolian, Nepali, Serbian (maybe same as Croatian?), Telugu

### ISSUE THREAD

**Issue by BLKSerene** [fergiemcdowall/stopword#292]
Hi, thanks for keep maintaining this project. Have you considered adding stop words for more languages from [extra-stopwords](https://github.com/Xangis/extra-stopwords)?

Theses languages are currently missing:
Albanian, Belarusian, Icelandic, Mongolian, Nepali, Serbian (maybe same as Croatian?), Telugu

**Comment by eklem** [comment]
Thanks! I'll add them. I'm in the middle of creating Sami stopwords, but I'll add them after that. I'll check if Croatian and Serbian are the same or not. Thanks for checking the difference and creating an issue!
