### ISSUE TITLE
licenses.txt is causing some problems

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#297]
Makes GitHub be ambiguous about which license the library has.

**Comment by eklem** [comment]
Quality meter on npmjs went from 39% to 61%, so working. Just moved the file to ./src folder and changed rollup config.

**Comment by fergiemcdowall** [comment]
Where does the NPM quality score for stopword live?

**Comment by eklem** [comment]
Live? In the search result. Middle of those three lines. I think it has something to say for the search result scoring.
<img width="865" alt="Screenshot 2022-09-24 at 15 53 40" src="https://user-images.githubusercontent.com/236656/192101779-e3a0ccbb-c1f7-4504-b35b-35ca477ff3e1.png">

**Comment by fergiemcdowall** [comment]
Thanks 👍
