### ISSUE TITLE
Incorrect main/module/exports specified in its package.json - mjs

### ISSUE THREAD

**Issue by bdart** [fergiemcdowall/stopword#304]
Hi there,

I tried to import it in a vite/typescript setup and got this error message:

> Failed to resolve entry for package "stopword". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "stopword". The package may have incorrect main/module/exports specified in its package.json.

I guess the package.json should point to the .mjs file rather than the non-existing .js on this line, right?

https://github.com/fergiemcdowall/stopword/blob/c2619989f702b5f374d0b01d15e5cb60fdda4163/package.json#L6

**Comment by fergiemcdowall** [comment]
Yes, that would seem to be correct- it should be fixed as per your description. Feel free to submit a PR if you want to claim the glory :)

**Comment by fergiemcdowall** [comment]
I can also fix the error next week sometime

**Comment by bdart** [comment]
> Yes, that would seem to be correct- it should be fixed as per your description. Feel free to submit a PR if you want to claim the glory :)

🙏 I will submit a PR, thank you

**Comment by eklem** [comment]
Great, thanks! I'll fix it now.

**Comment by eklem** [comment]
Fixed in [v2.0.7](https://github.com/fergiemcdowall/stopword/releases/tag/v.2.0.7) and published to NPM, thanks for the issue, @bdart!
