### ISSUE TITLE
Enable tree shaking

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/stopword#316]
I am trying to [tree shake](https://webpack.js.org/guides/tree-shaking/) `stopword`

At the moment, when using a bundler such as Webpack or Rollup `stopword` will always include _**all**_ lists of stopwords whether they are used or not. This means that bundled applications that include stopword will often be much larger than necessary.

**Example**
In [this gist](https://gist.github.com/fergiemcdowall/aa275a01e18bffb308234f31221abe01), the compiled output of `npm test` includes all languages even though it should only include English stopwords.

**The Fix**
Updating `package.json` as follows ->

```javascript
{
// ...
  "main": "./src/stopword.js",
  "module": "./src/stopword.js",
  "browser": "./src/stopword.js",
// ...
}
```

However- we have to make sure that the jsdeliver version continues to be generated

**Comment by fergiemcdowall** [comment]
If I understand correctly, we only have to keep the `/dist` folder as-is and publish to npm in order for it to appear on jsdelivr?

**Comment by fergiemcdowall** [comment]
published a release candidate for testing purposes -> `stopword@3.0.0-rc1`

**Comment by eklem** [comment]
I'm not sure, but it may be that part of the change made Jsdelivr use go to almost zero.

<img width="309" alt="Screenshot 2023-12-12 at 07 18 30" src="https://github.com/fergiemcdowall/stopword/assets/236656/55d8a2d5-90e1-4a35-970a-49e7d793f348">

Jsdelivr statistics was going down quite a lot, but not in that order of magnitude. Anyway, it could be coincidental. The most used file in v2.0.8 looks identical in v3.0.0-rc1.

https://cdn.jsdelivr.net/npm/stopword@2.0.8/dist/stopword.umd.min.js
https://cdn.jsdelivr.net/npm/stopword@3.0.0-rc1/dist/stopword.umd.min.js

**Comment by fergiemcdowall** [comment]
Hmm- strange. Publishing to npm with the tag `next` _should_ have no effect on jsdelivr, but maybe I am wrong?

I can see that the value of https://cdn.jsdelivr.net/npm/stopword@3.0.0-rc1 is incorrect. It should probably be the same as https://cdn.jsdelivr.net/npm/stopword@2.0.8 (pointing to the umd file in /dist).

I will upload a 3.0.0-rc2 version where package.json includes the line `"jsdelivr": "./dist/stopword.umd.js",` as per [the docs](https://www.jsdelivr.com/documentation). Hopefully that will fix https://cdn.jsdelivr.net/npm/stopword@3.0.0-rc2 which will then make downloads work again.

Its worth a try at least! 😅

**Comment by fergiemcdowall** [comment]
https://cdn.jsdelivr.net/npm/stopword@3.0.0-rc2 looks better, so _maybe_ downloads will pick up again..?😅

**Comment by eklem** [comment]
Nice! Hopefully it will =)

**Comment by eklem** [comment]
I'm guessing that either the change had nothing to do with the decline in use of JsDelivr as CDN, or that it was one user that has switched to another way of using the library. Or if it wasn't important for them, they have found another solution.

**Comment by fergiemcdowall** [comment]
Its very strange that the downloads should change so much, but yes, we may just have lost one "megauser"

**Comment by eklem** [comment]
I think you can release it as a proper v3.0 now.

**Comment by fergiemcdowall** [comment]
Just published on npm (will propagate out to jsdelivr)

**Comment by fergiemcdowall** [comment]
Possibly- will take a look.
