### ISSUE TITLE
Problem with mixed license types

### ISSUE THREAD

**Issue by msageryd** [fergiemcdowall/stopword#323]
The project is MIT, but the language files seems to differ depending on the language. I have found MIT, Apache and CC BY-SA in the language files.

I'm guessing that the intention is to have MIT everywhere since the project is MIT. Strictly, I don't hink I can only use MIT and Apache language files in my MIT project. I'm not sure though..

**Comment by eklem** [comment]
Thanks. Yes we've used a lot of different sources, but I see that CC BY-SA can be a problem. It's only Danish and Swedish language. I guess we should try to replace those two by either generating stopword lists or find some others. Would that help?
