### ISSUE TITLE
Replace Danish and Swedish languages with something non-CC-BY-SA license

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#324]
Best would be to find lists of stopwords with proper licenses or we need to generate it. I'll have a look around first.

https://github.com/fergiemcdowall/stopword/issues/323

**Comment by msageryd** [comment]
I found a Swedish repo with language resources, including stopwords, free to use.
Here is the repo: https://github.com/peterdalle/svensktext

There is no licence file, but the text states that you can use the data freely.
https://github.com/peterdalle/svensktext/blob/master/README.md#vill-du-anv%C3%A4nda-datan-g%C3%B6r-en-kopia

More specifically, here is a csv with Swedish stop words, free to use:
https://github.com/peterdalle/svensktext/blob/master/stoppord/stoppord.csv

I can make a PR out of this, but I won't have time for a couple of days.

**Comment by eklem** [comment]
Cool, we'll try that route! If you don't have time, I'll give it a go.

**Comment by msageryd** [comment]
The fact that there was no license file in the repo I found might be a problem, as you cannot slap an MIT license on material which does not state the license.

I found another resource which is all MIT and created a PR.

I don't know how important the sort order is for the stopwords. My PR consists of alphabetically sorted words. I think I read somewhere in this repo that the words are sorted by how usual they are.

**Comment by msageryd** [comment]
I see now that stopwords-iso alread is one of your sources. Is there any particular reason for not taking Swedish and Danish words from stopwords-iso?

**Comment by eklem** [comment]
I guess I added the Danish and Swedish list before I found stopwords-iso. I'll add them from there. Maybe later today, or tomorrow.

**Comment by eklem** [comment]
Oh, you've already gotten a PR in, thanks!

**Comment by eklem** [comment]
So, just needed to fix the tests, and now v3.1.0 is published to NPM. Thanks for the PR!

For the sort order, I've tried to have them in the frequency order. Then you can have long lists, and cut them off. But it is most probably not important and will never be used.

**Comment by eklem** [comment]
@msageryd Just open a new issue if you have any more problems.

**Comment by eklem** [comment]
@msageryd Needed to publish v3.1.1, since I forgot to update 3rd-party.txt witch contains the CC BY-SA license text for Swedish and Danish. Now they are correct too.

**Comment by msageryd** [comment]
Thanks Espen.
Now I can safely bundle all languages in my MIT project.

**Comment by fergiemcdowall** [comment]
🚀🚀🚀

**Comment by eklem** [comment]
Thanks for both notifying us and creating a PR Michael!
