### ISSUE TITLE
possibility to limit amount of stopwords in use?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#34]
Was thinking that needs for stopwords wary, and that it may be nice to set a limit on how many from the list that should be used.

For this to work, the arrays needs to be sorted in most to least used words.

This also fits nicely with a stopword trainer, if we get to make that.

**Comment by fergiemcdowall** [comment]
The problem is ordering the stopword lists by usage. If we could do that, it would then be pretty trivial to do something like `sw.en.slice(0, 10)`.

**Comment by eklem** [comment]
Ok, I'll play around with streams over at [stopword-trainer](https://github.com/eklem/stopword-trainer) =)
