### ISSUE TITLE
StopWords Russian

### ISSUE THREAD

**Issue by Haski-server** [fergiemcdowall/stopword#37]
Use the stop word from the stopwords-ru package.
More words in the repository https://github.com/stopwords-iso

**Comment by eklem** [comment]
Is that one a good list of Russian stopwords you think?

**Comment by Haski-server** [comment]
Partly good, as there are words not related to them. For example, the numbers can be replaced by a written version.

**Comment by eklem** [comment]
Ok, when I add it, could you make the small addition of written numbers?

**Comment by eklem** [comment]
Later, I can also [generate a bigger and frequency sorted list of stopwords based on ru.wikipedia.org](https://github.com/fergiemcdowall/stopword/issues/38). But that's a job that takes a bit more time.

**Comment by Haski-server** [comment]
Here is the list I often use. In this list, words that do not affect the meaning of the text or do not significantly change the meaning. Perhaps it is worth to supplement it a little.
I have a little studied the list of Russian words (https://github.com/stopwords-iso), and I came to the conclusion that there are words there which the absence can strongly spoil the meaning.

`['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'уж', 'вам', 'сказал', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'этом', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'были', 'куда', 'всех', 'никогда', 'сегодня', 'можно', 'при', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'эту', 'моя', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между', 'это', 'лишь']
`

**Comment by eklem** [comment]
Nice, thanks!

**Comment by eklem** [comment]
Sorry for the long wait. Will take a look soon!

**Comment by eklem** [comment]
So, who can I set a s copyright-holder and under what kind of license? MIT?

**Comment by eklem** [comment]
https://github.com/fergiemcdowall/stopword/commit/4126b11a99eb7ff26a2780200d405fed7506f48f
