### ISSUE TITLE
Add isStopWord() to filter word by word

### ISSUE THREAD

**Issue by flesler** [fergiemcdowall/stopword#39]
^

**Comment by eklem** [comment]
Not fully sure I understand?

**Comment by flesler** [comment]
```js
exports.isStopWord = function(token, stopwords) {
  stopwords = stopwords || defaultStopwords
  if (typeof tokens !== 'object' || typeof stopwords != 'object'){
    throw new Error ('expected Arrays try: removeStopwords(Array[, Array])')
  }
  return stopwords.indexOf(token.toLowerCase()) !== -1
}

exports.removeStopwords = function(tokens, stopwords) {
  return tokens.filter(function (value) {
    return !exports.isStopWord(value, stopwords)
  })
}
```

**Comment by eklem** [comment]
Sorry for slow response here, @flesler . Do you have a use-case so I can understand why? What's your need for this?

**Comment by flesler** [comment]
Sure, if you want to integrate this to something else, like [compromise](https://github.com/spencermountain/compromise) you need to filter by word.

Another use case, you might want to just highlight stop words, not remove them. This library could still satisfy that need if you just expose this.

**Comment by eklem** [comment]
I'll have a go at this soon!

**Comment by eklem** [comment]
Need to do a little benchmarking old/new code.

**Comment by eklem** [comment]
If this is still interesting, I can create another library using the stopword lists from this one? Closing for now, please open if you need it.
