### ISSUE TITLE
ES6 `const`

### ISSUE THREAD

**Issue by ulfryk** [fergiemcdowall/stopword#43]
Please remove `ES6` features from `main` library ( `const` in first line ) - there is a way to release both for ES5 targets and ES6 at once -> https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for

**Comment by eklem** [comment]
Thanks, @ulfryk !
I'll look into that. Would it be okay if we downgraded to `var` in the mean time?

**Comment by eklem** [comment]
0.1.11 is out on [npmjs](https://www.npmjs.com/package/stopword/v/0.1.11) 😄
