### ISSUE TITLE
Additional stopwords and tools

### ISSUE THREAD

**Issue by dohliam** [fergiemcdowall/stopword#49]
Are you aware of the [stopwords-json](https://github.com/6/stopwords-json) project which already has json-format lists of stopwords for 50 languages? This would be an easy way to expand the list of languages supported without recreating the lists for each language from scratch.

I have also created some scripts to manage stoplist creation as part of the [more-stoplists](https://github.com/dohliam/more-stoplists/tree/master/scripts) project (which has now been merged into stoplists-json). Some of these may be useful for your work -- in addition to [stopword-trainer](https://github.com/eklem/stopword-trainer) of course.

**Comment by eklem** [comment]
Yes,
I'm aware of it, and I think some of the languages in `stopword` are from the `stopwords-json` project. Not sure why I haven't just copied them all, but maybe I should do that!

There's an extra reason for generating stopword lists myself, and that is frequency sorting of the stopwords. That means they can be used more or less aggressively by using the whole list or just a portion of it.

**Comment by eklem** [comment]
And cool with the african languages!

**Comment by dohliam** [comment]
Great, thanks for letting me know about the reasoning behind the project. It makes sense to look at frequency for the reasons you mentioned.

Given that you are looking for frequency-arranged stoplists, you may be interested to know that this is in fact exactly how the lists in the more-stoplists project were generated. All the frequency-sorted data is available in that same repo -- you can find it in each of the subdirectories which are labelled by ISO code.

So for example, you will find a ready-made list of frequency-sorted stopwords for Swahili [here](https://github.com/dohliam/more-stoplists/blob/master/sw/sw.txt), and the full frequency list of Swahili words from the corpus (with frequencies listed on the left) [here](https://github.com/dohliam/more-stoplists/blob/master/sw/sw_frequency_list.txt).

I will be adding Amharic and Oromo stoplists soon, and I'll make those available from the same repo once they are ready.

There is also a similar repo for a Hawaiian corpus which also has a frequency-sorted stoplist of Hawaiian words [here](https://github.com/dohliam/hawaiian-corpus/blob/master/data/stoplist_haw.txt).

There might be more that I have forgotten, but hope that helps for now! :smile:

**Comment by eklem** [comment]
Cool, that's great news. i'll get all the languages in from `more-stoplists`. Also, I'll add from `stopwords-json` and just mark those that are frequency sorted in the overview.

**Comment by eklem** [comment]
@dohliam Would you be able to verify that the test's I set up are correct?

**Comment by dohliam** [comment]
@eklem Sure! I'll try to look at these this week. By the way, are the tests you are referring to [these ones](https://github.com/fergiemcdowall/stopword/blob/master/test/test.js)?

**Comment by eklem** [comment]
Yepp =) Haven't made any new ones, but that's what's needed to get new languages in.

**Comment by eklem** [comment]
In the process of adding your African stopword lists, three left =)

**Comment by eklem** [comment]
@dohliam, do you have some sample text in Lugbara for tests.

**Comment by dohliam** [comment]
Great to hear you were able to use the existing stop lists! There is indeed a collection of sample text in both forms of Lugbara:

* [Official orthography](https://github.com/global-asp/asp-source/tree/master/lgg-official)
* [Unofficial orthography](https://github.com/global-asp/asp-source/tree/master/lgg) (i.e., without diacritics)

**Comment by eklem** [comment]
I got them all out! I'll continue with the lists from [stopword-json](https://github.com/6/stopwords-json) at a later stage.
