### ISSUE TITLE
Stopwords file for chinese

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/stopword#5]
We should add stopwords for more languages. I'll need some help to create A chinese stopword-file, since I can't make sense of it myself. 

Could be based on https://invokeit.wordpress.com/frequency-word-lists/#comment-9707 or https://github.com/6/stopwords/blob/master/dist/zh.json
- [ ] Chinese

**Comment by eklem** [comment]
So, creating the file is easy, but I need some tests. @fergiemcdowall Is it okay to add without tests, and then I can create some tests later, when issues starts to emerge?

I'll base it on this:
https://github.com/6/stopwords-json/blob/master/dist/zh.json

**Comment by eklem** [comment]
Sorry, this one already exists.

**Comment by fergiemcdowall** [comment]
It is _generally_ better to add with tests if possible :)

**Comment by eklem** [comment]
I know, and I did that for Swedish and Danish =)
A little chicken and egg problem since I don't know any Chinese simplified, but we already have the JSON-file, I just saw and [old, open issue](https://github.com/fergiemcdowall/stopword/issues/5) and didn't check.
