### ISSUE TITLE
add Myanmar stopword 

### ISSUE THREAD

**Issue by Kyaw-Zin-Thant** [fergiemcdowall/stopword#51]
Plz add Myanmar stop words in package.

**Comment by eklem** [comment]
Yes! Is there a Wikipedia-site in Myanmar language?

**Comment by eklem** [comment]
This one, I'm guessing: [ဗဟိုစာမျက်နှာ](https://my.wikipedia.org/wiki/%E1%80%97%E1%80%9F%E1%80%AD%E1%80%AF%E1%80%85%E1%80%AC%E1%80%99%E1%80%BB%E1%80%80%E1%80%BA%E1%80%94%E1%80%BE%E1%80%AC)

**Comment by Kyaw-Zin-Thant** [comment]
support Myanmar in stopword node modules?

**Comment by eklem** [comment]
Yes, sorry. I just asked about the Wikipedia site since I need a dataset with the language for the [stopword-trainer](https://github.com/eklem/stopword-trainer) to create a stopword list.

If you can help verify the final list of stopwords, I'll create it.

**Comment by Kyaw-Zin-Thant** [comment]
I will send Myanmar stopwords file. You can crate this in stopwords node modules

**Comment by eklem** [comment]
Ok, great. I'll add it.

**Comment by Kyaw-Zin-Thant** [comment]
[stopwords-my.txt](https://github.com/fergiemcdowall/stopword/files/2723432/stopwords-my.txt)

**Comment by Kyaw-Zin-Thant** [comment]
Thz for support

**Comment by eklem** [comment]
No problem. I'll add this later tonight (Central European time). 

Just one question: Is this list sorted alphabetically or most to least used stopwords (frequency sorted) ?

**Comment by Kyaw-Zin-Thant** [comment]
sorted alphabetically

**Comment by eklem** [comment]
Ok, thanks!

**Comment by Kyaw-Zin-Thant** [comment]
welcome

**Comment by eklem** [comment]
One more question: Who has copyright to the stopwords and what license is it under?

**Comment by Kyaw-Zin-Thant** [comment]
"မည်သူမဆို" စားႏိုုင္ပါတယ္ stopword is in semi colon . no lowercase no punctuation
no copyright. free for all

**Comment by eklem** [comment]
Cool, but could you make it a little longer or just add two or three sentences (with no punctuation)? So it's a more real test.

**Comment by Kyaw-Zin-Thant** [comment]
"မည်သူမဆို" "လာေရာက္" "စားသံုုး" " ႏိုင္သည္"   stopwords is in semi colon
Is it ok? 👍

**Comment by eklem** [comment]
I was thinking of a mix of stopwords and non-stopwords.

**Comment by eklem** [comment]
If you look at the test for the English stopword list, you have a sentence with 7 words, reduced to 4 words after stopwords removed:

```javascript
describe('general stopwordiness:', function () {
  it('should remove stopwords, should default to english, should preserve case', function () {
    const oldString = 'a really Interesting string with some words'.split(' ')
    const newString = sw.removeStopwords(oldString)
    should.exist(sw.removeStopwords(oldString))
    newString.should.eql([ 'really', 'Interesting', 'string', 'words' ])
  })
```

**Comment by eklem** [comment]
I don't get the tests to work, but the stopwords are there to use, with the language code `my`.
I haven't documented it since I'm not sure that it's fully working. Feel free to open this issue again.

**Comment by eklem** [comment]
Anyone have a list of words (string?) that I can test? Then I can officially add Myanmar to the library.

**Comment by eklem** [comment]
Got tests to work in [v1.0.11](https://github.com/fergiemcdowall/stopword/releases/tag/v1.0.11), but I think the list needs to be more comprehensive. [Looking into that](https://github.com/fergiemcdowall/stopword/issues/209).
