### ISSUE TITLE
accept arrays?

### ISSUE THREAD

**Issue by bingomanatee** [fergiemcdowall/stopword#6]
Is is possible to accept arrays as an input as well as text?

**Comment by eklem** [comment]
Hi @bingomanatee, @fergiemcdowall is on vacation right now, so I'm more guessing than coming with an authoritative answer. Looking at the tests, it seems there are only strings being used as input. What's the usecase for inputing an array?

**Comment by fergiemcdowall** [comment]
Hi @bingomanatee 

No, Arrays are not accepted, but they really should be because that way the string separator logic could be extracted out of the library. I am leaning towards a (semver happy) version bump which would alter the API to make Arrays the input format.

**Comment by fergiemcdowall** [comment]
In the meantime you can of course convert your Strings to Arrays using `.join`

**Comment by fergiemcdowall** [comment]
@bingomanatee `stopword` now accepts arrays rather than strings
