### ISSUE TITLE
Error: Cannot find module 'stopword'

### ISSUE THREAD

**Issue by ElectroP** [fergiemcdowall/stopword#64]
i installed stopword module still it is showing error

**Comment by eklem** [comment]
Hi @ElectroP !
Can you describe how to reproduce the error?

**Comment by ElectroP** [comment]
i created one project and then did npm install natural and also npm install stopword. While executing my node js file it is throwing above error

**Comment by eklem** [comment]
I need a bit more info, the specific steps. I did this, and it worked:

* Opened a console window
* `npm install stopword`
* `mkdir test-stopword`
* `nano index.js`
* pasted in ```
sw = require('stopword')
const oldString = 'a really Interesting string with some words'.split(' ')
const newString = sw.removeStopwords(oldString)
// newString is now [ 'really', 'Interesting', 'string', 'words' ]
console.log(newString)```
* ctrl+o (save)
* ctrl+x (exit)
* `node index.js`

And that gave me this result
```console
[ 'really', 'Interesting', 'string', 'words' ]
```

**Comment by eklem** [comment]
Or, you could create a package.json in your project and set stopword as a dependency and do `npm install` to get your dependencies installed within your project folder.

**Comment by ElectroP** [comment]
it worked thanks :)

**Comment by eklem** [comment]
Cool! Shout out if you have any more problems :-)
