### ISSUE TITLE
Stop words not recognized if punctuation

### ISSUE THREAD

**Issue by JeremyPouyet** [fergiemcdowall/stopword#7]
I don't know if it's the normal behavior, but stop words aren't recognized if non alpha characters are present in the string:

```
const oldString = 'This gift is for me'.split(' ')
console.log('=> ' + sw.removeStopwords(oldString, langToSw[lang]))
=> gift

const oldString = 'This gift is for me!'.split(' ')
console.log('=> ' + sw.removeStopwords(oldString, langToSw[lang]))
=> gift, me!
```

I know I can avoid this by using split(/[ !]/) but it starts becoming annoying because I have to list all possible characters and it can leads to loss of meaning in the text. For the same reason, I also don't want to remove all punctuation from the text.

**Comment by fergiemcdowall** [comment]
Yes, that is the correct behaviour, as far as I know you must use regex for this type of work. Have you investigated doing something with [.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) in order to preserve punctuation?

**Comment by JeremyPouyet** [comment]
I work with an important volume of data, using .replace is not efficient. But that's not a problem, I'll find another way to do this, thank you.

**Comment by fergiemcdowall** [comment]
Since you have a lot of data, I wonder if there is a smart way to do this with streams...
